apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lambda-api.fullname" . }}-secret
  labels:
    {{- include "lambda-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: "{{ uuidv4 }}"