apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lambda-api.fullname" . }}-rsa
  labels:
    {{- include "lambda-api.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ genPrivateKey "rsa" | b64enc }}