apiVersion: v1
kind: Service
metadata:
  name: {{ include "lambda-api.fullname" . }}
  labels:
    {{- include "lambda-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "lambda-api.selectorLabels" . | nindent 4 }}
  
  {{- if .Values.service.extraServiceSpec }}
  {{ toYaml .Values.service.extraServiceSpec | nindent 2 }}
  {{- end }}
