apiVersion: v1
kind: Service
metadata:
  name: {{ include "lambda-api.fullname" . }}
  labels:
    {{- include "lambda-api.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.dualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.dualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.dualStack.ipFamilyPolicy }}
{{- end}}

  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "lambda-api.selectorLabels" . | nindent 4 }}