{{- if and .Values.serviceMonitor .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lambda-auth.fullname" . }}-prometheus
  labels:
{{- with .Values.serviceMonitor.additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "lambda-auth.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scheme }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 6) . }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings: {{- toYaml .Values.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
{{- end }}