apiVersion: v1
kind: Service
metadata:
  name: {{ include "lambda-auth.fullname" . }}
  labels:
    {{- include "lambda-auth.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.dualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.dualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.dualStack.ipFamilyPolicy }}
{{- end }}

  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: mc
      protocol: TCP
      name: mc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics

  selector:
    {{- include "lambda-auth.selectorLabels" . | nindent 4 }}

