name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://charts.helm.sh/stable

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://edouard127.github.io/lambda-helm-charts/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"